version: "3"

services:

  telecom-zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    container_name: telecom-zookeeper

    ports:
      - "2182:2181"

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  telecom-kafka:
    image: confluentinc/cp-server:5.4.0
    container_name: telecom-kafka

    depends_on:
      - telecom-zookeeper

    ports:
      - "29093:29092"
      - "9093:9092"

    environment:

      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT:
        telecom-zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_ADVERTISED_LISTENERS:
        PLAINTEXT://telecom-kafka:29092,PLAINTEXT_HOST://localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1